#!/usr/bin/bash

dir="~/.config/rofi/"
uptime=$(uptime -p | sed -e 's/up //g')

rofi_command="rofi -theme $dir/powermenu.rasi"
shutdown="⏻ Shutdown"
reboot="󰜉 Restart"
lock=" Lock"
#suspend="󰤄 Sleep"
logout="﫼 Logout"

# Confirmation
confirm_exit() {
	rofi -dmenu\
		-i\
		-no-fixed-num-lines\
		-p "Are You Sure? : "\
		-theme $dir/confirm.rasi
}

# Message
mensaje() {
	rofi -theme "$dir/message.rasi" -e "Available Options  -  yes / y / no / n"
}

# Variable passed to rofi
options="$lock\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "Uptime: $uptime" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
		ans=$(confirm_exit &)
		if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
			systemctl poweroff
		elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
			exit 0
        else
			mensaje
        fi
        ;;
    $reboot)
		ans=$(confirm_exit &)
		if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
			systemctl reboot
		elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
			exit 0
        else
			mensaje
        fi
        ;;
    $lock)
		if [[ -f /usr/bin/i3lock-fancy ]]; then
			/usr/bin/i3lock-fancy
		fi
        ;;
    #$suspend)
	#	ans=$(confirm_exit &)
	#	if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
	#		systemctl suspend
	#	elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
	#		exit 0
    #   else
	#		mensaje
    #    fi
    #    ;;
    $logout)
		ans=$(confirm_exit &)
		if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
			if [[ "$DESKTOP_SESSION" == "awesome" ]]; then
				awesome-client 'awesome.quit()' 
			fi
		elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
			exit 0
        else
			mensaje
        fi
        ;;
esac
