#! /bin/bash

# Global Variables
if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "daku" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	POLYBAR="$HOME/.config/polybar/daku/config.ini"
fi 

if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "dakura" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	POLYBAR="$HOME/.config/polybar/dakura/colors.ini"
fi
WALLS=(~/Pictures/Wallpapers/*)

function select_wallpaper() {
	WALLPAPER=$(printf "%s\n" "${WALLS[RANDOM % ${#WALLS[@]}]}")
}

PREV=$(cat /dev/shm/previous.txt 2>/dev/null) 

while [[ "$WALLPAPER" == "$PREV" || "$WALLPAPER" == "" ]]
do
	#echo "[-] Wallpaper was repeated or is blank"
	select_wallpaper
done

echo $WALLPAPER > /dev/shm/previous.txt
killall feh 2>/dev/null

cat $POLYBAR | grep 'background = #14181d'
if [ $? == 0 ]; then
    feh --bg-fill $WALLPAPER
    exit
else
	/usr/local/bin/pywal $WALLPAPER
	feh --bg-fill "$(< "${HOME}/.cache/wal/wal")"
	exit
fi

