#! /bin/bash

WALLS=(~/Pictures/Wallpapers/*)

function select_wallpaper() {
	WALLPAPER=$(printf "%s\n" "${WALLS[RANDOM % ${#WALLS[@]}]}")
}

PREV=$(cat /dev/shm/previous.txt 2>/dev/null) 

while [[ "$WALLPAPER" == "$PREV" || "$WALLPAPER" == "" ]]
do
	#echo "[-] Wallpaper was repeated or is blank"
	select_wallpaper
done

echo $WALLPAPER > /dev/shm/previous.txt
killall feh 2>/dev/null

DAKU=$(cat $HOME/.config/polybar/config.ini | grep 'background = #14181d')
if [ $? != 0 ]; then
    feh --bg-fill $WALLPAPER
    exit
else
	/usr/local/bin/pywal $WALLPAPER
	exit
fi

